### ISSUE TITLE
How is SLD resolving startup(), layout() and resize()

### ISSUE THREAD

**Issue by gaurav21r** [sapienlab/sld#5]
Nice Project! We had a similar idea but stumbled upon the following:

When using Layout widgets like TabContainer etc. How (if at all) is sld handling calls to `startup()`, `layout()` etc? Especially when adding children with `addChild()`

**Comment by roro89** [comment]
Wow, Happy new Year! :sweat_smile:  Sorry, I forgot about respond to this thread.

Yeah, the Dojo community is poor in quantity, but has a very smart people.

About SLD Playground, I think that already is good as such. Their intention is just to demonstrate the capacities of SLD for creating IDE's. Maybe in the future. Thanks!
